### ISSUE TITLE
Not working in Samsung S10 +

### ISSUE THREAD

**Issue by alfonsoara77** [vuk/cordova-plugin-notch#2] opened 2019-08-28 18:02 UTC
Try to install it so that the notch works with ionic and what I read in the documentation is that it is just install it, right? Or should something be added in the config or run a function?

Thanks

**Comment by vuk** [comment] 2020-07-29 10:43
Duplicate of https://github.com/vuk/cordova-plugin-notch/issues/3

**Closed by vuk** 2020-07-29 10:43 UTC
